development:
    adapter: mysql2
    username: root
    database: actioncable_dev
    host: 127.0.0.1
production:
    adapter: mysql2
    username: <%= ENV['MYSQL_USERNAME'] %>
    password: <%= ENV['MYSQL_PASSWORD'] %>
    database: actioncable_prod
    host: <%= ENV['MYSQL_ADDRESS'] %>
